samplesfile: resources/samples.txt
star_genome_dir: reference/genome_dir
reference_gtf: /data1/shahs3/isabl_data_lake/assemblies/GRCh38/genes/genes.gtf # path to GTF
fastq_pathfile: resources/fastq_paths.tsv
genome_version: "hg38"
log_dir: logs
tmp_dir: tmp
